ekf_filter_node:
  ros__parameters:
    frequency:      50.0
    sensor_timeout: 0.3
    two_d_mode:     true

    map_frame:      reference
    odom_frame:     reference
    base_link_frame:gps_antenna
    world_frame:    reference

    imu0:  /imu/processed
    imu0_config: [false,false,false,
                  false,false,true,
                  false,false,false,
                  false,false,true,
                  true,true,false]
    imu0_remove_gravitational_acceleration: true

    odom0: /odometry/gps               # navsat 출력
    odom0_config: [true,true,false,
                   false,false,false,
                   false,false,false,
                   false,false,false,
                   false,false,false]
    odom0_differential: false

    use_sim_time: true
