ekf_fusion_node:
  ros__parameters:
    # 프레임 ID 설정
    world_frame_id: "odom"
    base_frame_id: "base_link"
    gnss_frame_id: "gps"
    imu_frame_id: "imu_link"
    
    # 일반 설정
    update_rate: 50.0       # EKF 업데이트 주기 (Hz)
    # update_rate:
    #   높일수록 더 빠른 응답을 얻을 수 있지만 CPU 사용량이 증가함
    #   10-50Hz 범위가 적당함
    #   IMU 데이터 속도의 약 1/2~1/3 정도로 설정하는 것이 좋음
    publish_tf: true        # TF 변환 발행 여부
    
    # 자세 추정 관련
    mag_declination: -8.0    # 자기 편각 (도)
    # 자기 편각:
    #   현재 위치의 자기 편각을 정확히 설정하면 방향 추정 정확도가 향상됨
    #   한국의 경우 약 -8도 (서편각)
    #   정확한 값은 NOAA 자기장 계산기에서 확인
    use_magnetic_declination: false  # 자기 편각 보정 사용 여부
    use_gnss_heading: true  # GNSS 헤딩을 사용할지 여부 (속도가 충분히 있을 때)
    # use_gnss_heading:
    #   true: 차량이 충분한 속도로 이동 중일 때 GNSS 방향각을 사용
    #   false: 항상 EKF 추정 헤딩 사용
    #   직선 주행이 많은 경우 true 권장
    #   제자리 회전이 많은 경우 false 권장
    min_speed_for_gnss_heading: 0.08  # GNSS 헤딩 사용 임계값 - 0.08m/s (코드에서 하드코딩됨)
    zupt_speed_threshold: 0.1   # ZUPT 비활성화 상태 - 사용 안 함
    zupt_noise_scale: 1.0       # ZUPT 비활성화 - 노이즈 스케일 원상복구
    zupt_gyro_threshold: 0.01   # 정지 감지 자이로 임계값 (rad/s) - 더 엄격
    zupt_accel_threshold: 0.1   # 정지 감지 가속도 임계값 (m/s^2) - 더 엄격
    # min_speed_for_gnss_heading:
    #   너무 낮게 설정하면 정지 상태에서 노이즈로 인한 방향 변동 발생
    #   너무 높게 설정하면 저속에서 방향 추정 품질 저하
    #   0.3~1.0 m/s 범위 권장


    # === 실험용 EKF 파라미터 ===
    
    # 프로세스 노이즈 파라미터 (값이 클수록 측정값을 더 신뢰함)
    accel_noise: 0.05       # 가속도계 출력 노이즈의 표준편차 (m/s^2)
    # accel_noise: 
    #   가속도계의 노이즈 수준을 나타냄 
    #   값이 클수록 가속도계 측정값을 덜 신뢰함 
    #   부드러운 움직임이 필요하면 값을 높임 (0.1-0.5) 
    #   반응성이 필요하면 값을 낮춤 (0.01-0.05) 
    #   센서 테스트: 정지 상태에서 가속도계 출력의 표준편차를 측정하여 설정 
    gyro_noise: 0.00175     # 자이로 출력 노이즈의 표준편차 (rad/s)
    # gyro_noise: 
    #   자이로스코프의 노이즈 수준을 나타냄 
    #   값이 클수록 자이로 측정값을 덜 신뢰함 
    #   부드러운 자세 추정이 필요하면 값을 높임 (0.005-0.01) 
    #   빠른 회전 추적이 필요하면 값을 낮춤 (0.0005-0.002) 
    #   센서 테스트: 정지 상태에서 자이로 출력의 표준편차를 측정하여 설정 
    accel_bias_noise: 0.01  # 가속도계 바이어스 표준편차 (m/s^2)
    gyro_bias_noise: 0.00025 # 자이로 바이어스 표준편차 (rad/s)
    # accel_bias_noise / gyro_bias_noise: 
    #   바이어스의 랜덤 워크 특성을 모델링 
    #   값이 클수록 바이어스가 더 빨리 변할 것으로 예상 
    #   고품질 IMU는 낮은 값 사용 (0.001-0.005 / 0.00005-0.0001) 
    #   저렴한 IMU는 높은 값 사용 (0.01-0.05 / 0.0005-0.001) 
    #   장기 테스트: 온도 안정화 후 장시간 바이어스 변화를 관찰하여 조정 
    accel_bias_tau: 100.0   # 가속도계 바이어스 시간 상수 (s)
    gyro_bias_tau: 50.0     # 자이로 바이어스 시간 상수 (s)
    # accel_bias_tau / gyro_bias_tau: 
    #   바이어스의 상관 시간 (높을수록 바이어스가 천천히 변함) 
    #   고품질 IMU는 높은 값 사용 (300-600s / 100-300s) 
    #   저렴한 IMU는 낮은 값 사용 (50-100s / 30-50s) 
    #   실험 조정: 바이어스 추정이 얼마나 빨리 수렴하는지 관찰하며 조정 


    # 측정 노이즈 파라미터 (값이 작을수록 GPS를 더 신뢰함)
    gps_pos_noise_ne: 0.2   # GPS 위치 노이즈 표준편차 (북-동) (m)
    gps_pos_noise_d: 1.0    # GPS 위치 노이즈 표준편차 (하) (m)
    # gps_pos_noise_ne / gps_pos_noise_d: 
    #   GPS 위치 측정의 표준편차 
    #   값이 작을수록 GPS 위치를 더 신뢰함 
    #   개방된 공간: 낮은 값 (1.0-3.0m / 3.0-6.0m) 
    #   도심/숲: 높은 값 (5.0-10.0m / 10.0-15.0m) 
    #   RTK GPS: 매우 낮은 값 (0.1-0.5m / 0.2-1.0m) 
    gps_vel_noise_ne: 0.5   # GPS 속도 노이즈 표준편차 (북-동) (m/s)
    gps_vel_noise_d: 1.0    # GPS 속도 노이즈 표준편차 (하) (m/s)
    # gps_vel_noise_ne / gps_vel_noise_d: 
    #   GPS 속도 측정의 표준편차 
    #   값이 작을수록 GPS 속도를 더 신뢰함
    #   일반적인 범위: 0.1-2.0 m/s
    #   속도가 부드럽지 않으면 값을 높이세요
    #   가속/감속 추적이 부정확하면 값을 낮추세요
    #   공분산 정보가 이미 메시지에 포함되어 있으면 해당 값이 우선 적용됨
    
    
    # 초기 공분산 파라미터 (초기 불확실성)
    init_pos_unc: 10.0      # 초기 위치 불확실성 (m)
    init_vel_unc: 1.0       # 초기 속도 불확실성 (m/s)
    # init_pos_unc / init_vel_unc: 
    #   초기 위치/속도 불확실성 
    #   일반적으로 이 값들은 GPS 정확도에 따라 설정 
    #   위치: 정지 시작 5-10m, 이동 중 시작 20-50m 
    #   속도: 정지 시작 0.1-0.5m/s, 이동 중 시작 1-5m/s 
    init_att_unc: 0.34906   # 초기 자세 불확실성 (rad), ~20도
    init_hdg_unc: 3.14159   # 초기 헤딩 불확실성 (rad), ~180도
    # init_att_unc / init_hdg_unc: 
    #   초기 롤/피치 및 요 불확실성 
    #   롤/피치: IMU 품질에 따라 0.1-0.5rad 
    #   헤딩: 초기 방향 정보 없을 때 π rad (180도) 
    #   자기장 또는 초기 정렬 정보가 있으면 헤딩 불확실성 낮춤 (0.1-0.5rad) 
    init_accel_bias_unc: 0.981 # 초기 가속도계 바이어스 불확실성 (m/s^2)
    init_gyro_bias_unc: 0.01745 # 초기 자이로 바이어스 불확실성 (rad/s)
    # init_accel_bias_unc / init_gyro_bias_unc: 
    #   초기 가속도/자이로 바이어스 불확실성 
    #   가속도계: 일반적으로 0.5-1.0 m/s² 
    #   자이로: 일반적으로 0.01-0.05 rad/s 
    #   센서 품질에 따라 조정
    
    # IMU Calibration 파일 경로 (패키지 상대 경로)
    imu_calibration_file: ""
    # imu_calibration_file:
    #   IMU bias 및 Allan variance 분석 결과가 포함된 JSON 파일 경로
    #   예: "config/improved_imu_calibration.json" (패키지 상대 경로)
    #   빈 문자열("")로 설정하면 calibration 파일을 사용하지 않음