imu_preprocess_node:
  ros__parameters:
    # Pre-calibrated IMU bias values
    use_precalibrated_bias: true
    
    # Accelerometer bias [m/s²]
    bias_acc_x: -0.20908
    bias_acc_y: 0.02659
    bias_acc_z: -0.24675
    
    # Gyroscope bias [rad/s]
    bias_gyro_x: 0.00837
    bias_gyro_y: -0.01812
    bias_gyro_z: -0.02142
    
    # Low-pass filter settings
    lpf_cutoff: 1.0  # 0 to disable LPF

    # Runtime gravity compensation
    remove_gravity: true       # true로 하면 orientation을 이용해 중력 보정 수행
    gravity_magnitude: 9.81     # [m/s^2]
